# Use the official Node.js image from Docker Hub
FROM node:22.11.0-alpine

# Set working directory
WORKDIR /app

# Copy everything including .env (generated by GitHub Actions before build)
COPY . .

# Ensure start script is executable
RUN chmod +x /app/start.sh

# Install PostgreSQL client and bash
RUN apk add --no-cache postgresql-client bash

# Make sure both services get the environment file
# Copy .env to both service directories
RUN cp /app/.env /app/user-service/.env && \
    cp /app/.env /app/masterData-service/.env

# Install and build user-service
WORKDIR /app/user-service
RUN npm install --legacy-peer-deps \
 && npm run prisma:generate \
 && npm run build

# Install and build masterData-service
WORKDIR /app/masterData-service
RUN npm install --legacy-peer-deps \
 && npm run prisma:generate \
 && npm run build

# Expose ports
EXPOSE 3001 3002

# Run services
CMD ["sh", "-c", "/app/start.sh"]
