name: Deploy to GCP VM

on:
  push:
    branches:
      - "main"

jobs:
  # ---------------------------------------------------------
  # JOB 1: CHECKOUT
  # ---------------------------------------------------------
  checkout:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Restore .env from BASE64 Secret
      - name: Create .env from secret
        run: |
          echo "${{ secrets.ENV_FILE_BASE64 }}" | base64 --decode > .env
          cat .env

  # ---------------------------------------------------------
  # JOB 2: Build & Push Docker image
  # ---------------------------------------------------------
  build-and-push:
    needs: checkout
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Configure Docker for GAR
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build Docker image
        run: docker build -t us-central1-docker.pkg.dev/traeta-data/traeta-gar/traeta-backend:latest .

      - name: Push Docker image
        run: docker push us-central1-docker.pkg.dev/traeta-data/traeta-gar/traeta-backend:latest

  # ---------------------------------------------------------
  # JOB 3: SSH to VM and Deploy using docker-compose
  # ---------------------------------------------------------
  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Download SSH Key
        run: |
          echo "${{ secrets.GCP_SSH_PRIVATE_KEY }}" > private_key
          chmod 600 private_key

      - name: Create .env on VM and Deploy
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key ${{ secrets.GCP_VM_USER }}@${{ secrets.GCP_VM_HOST }} << 'EOF'
          echo "${{ secrets.ENV_FILE_BASE64 }}" | base64 --decode > /home/${{ secrets.GCP_VM_USER }}/traeta/.env
          cd /home/${{ secrets.GCP_VM_USER }}/traeta
          docker-compose down || true
          docker pull us-central1-docker.pkg.dev/traeta-data/traeta-gar/traeta-backend:latest
          docker-compose up -d --force-recreate
          EOF
