name: Build, Push Docker to GAR, and Deploy

on:
  push:
    branches:
      - "main"

jobs:
  checkout:
    runs-on: self-hosted-gcp
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

  build_and_push:
    needs: checkout
    runs-on: self-hosted-gcp

    steps:
      - name: Checkout code
      ...


      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .env from GitHub Secret
        run: |
          cat << 'EOF' > .env
${{ secrets.MY_ENV_VARS }}
EOF

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Configure Docker for GAR
        run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: Build Docker Image
        run: docker build -t us-central1-docker.pkg.dev/traeta-data/traeta-gar/traeta-backend:latest .

      - name: Push Docker Image
        run: docker push us-central1-docker.pkg.dev/traeta-data/traeta-gar/traeta-backend:latest

  deploy:
    needs: build_and_push
    runs-on: self-hosted-gcp

    defaults:
      run:
        working-directory: /home/ganesh_cheekurthi/actions-runner/_work/new-project-repo/new-project-repo

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .env from GitHub Secret
        run: |
          cat << 'EOF' > .env
${{ secrets.MY_ENV_VARS }}
EOF

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Configure Docker for GAR
        run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: Pull latest image
        run: docker pull us-central1-docker.pkg.dev/traeta-data/traeta-gar/traeta-backend:latest

      - name: Ensure Docker Compose Installed
        run: |
          if ! command -v docker-compose &> /dev/null; then
            sudo apt-get update
            sudo apt-get install -y docker-compose
          fi

      - name: Deploy
        run: |
          docker-compose down || true
          docker-compose up -d
          echo "✅ Deployment Successful!"
