name: Deploy to GCP VM

on:
  push:
    branches:
      - "main"

jobs:
  # ---------------------------------------------------------
  # JOB 1: CHECKOUT + RESTORE .env
  # ---------------------------------------------------------
  checkout:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore .env from base64 secret (Secure)
        run: |
          echo "${{ secrets.ENV_FILE_BASE64 }}" | base64 --decode > .env

      - name: Mask .env values (Prevent showing in logs)
        shell: bash
        run: |
          while IFS='=' read -r key value; do
            [[ -n "$value" ]] && echo "::add-mask::$value"
          done < .env

  # ---------------------------------------------------------
  # JOB 2: Build & Push Docker image to GAR
  # ---------------------------------------------------------
  build-and-push:
    needs: checkout
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Configure Docker for GAR
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build Docker image
        run: docker build -t us-central1-docker.pkg.dev/traeta-data/traeta-gar/traeta-backend:latest .

      - name: Push Docker image
        run: docker push us-central1-docker.pkg.dev/traeta-data/traeta-gar/traeta-backend:latest

  # ---------------------------------------------------------
  # JOB 3: SSH to GCP VM & DEPLOY
  # ---------------------------------------------------------
  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Prepare SSH Key
        run: |
          echo "${{ secrets.GCP_SSH_PRIVATE_KEY }}" > private_key
          chmod 600 private_key

      - name: Deploy to VM
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key ${{ secrets.GCP_VM_USER }}@${{ secrets.GCP_VM_HOST }} << 'EOF'
          echo "${{ secrets.ENV_FILE_BASE64 }}" | base64 --decode > /home/${{ secrets.GCP_VM_USER }}/traeta/.env
          cd /home/${{ secrets.GCP_VM_USER }}/traeta
          docker-compose down || true
          docker pull us-central1-docker.pkg.dev/traeta-data/traeta-gar/traeta-backend:latest
          docker-compose up -d --force-recreate
          EOF
