name: Deploy to GCP VM

on:
  push:
    branches:
      - "main"

jobs:
  # ---------------------------------------------------------
  # JOB 1: CHECKOUT
  # ---------------------------------------------------------
  checkout:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Restore .env from BASE64 Secret
      - name: Create .env locally (for reference only)
        run: |
          echo "${{ secrets.ENV_FILE_BASE64 }}" | base64 --decode > .env
          sed -n '1,5p' .env
          echo "✅ .env restored locally (not used for deploy)"

  # ---------------------------------------------------------
  # JOB 2: Build & Push Image to GAR
  # ---------------------------------------------------------
  build-and-push:
    needs: checkout
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Configure Docker to push to GAR
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build Docker image
        run: docker build -t us-central1-docker.pkg.dev/traeta-data/traeta-gar/traeta-backend:latest .

      - name: Push Docker image
        run: docker push us-central1-docker.pkg.dev/traeta-data/traeta-gar/traeta-backend:latest

  # ---------------------------------------------------------
  # JOB 3: SSH to VM and Deploy using docker-compose
  # ---------------------------------------------------------
  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Prepare SSH Key
        run: |
          echo "${{ secrets.GCP_SSH_PRIVATE_KEY }}" > private_key
          chmod 600 private_key

      - name: Deploy to VM
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key ${{ secrets.GCP_VM_USER }}@${{ secrets.GCP_VM_HOST }} << 'EOF'
          cd /home/${{ secrets.GCP_VM_USER }}/new-project-repo

          echo "🔄 Updating .env..."
          echo "${{ secrets.ENV_FILE_BASE64 }}" | base64 --decode > .env

          echo "🚀 Pulling latest image..."
          docker pull us-central1-docker.pkg.dev/traeta-data/traeta-gar/traeta-backend:latest

          echo "🔄 Restarting services..."
          docker-compose down || true
          docker-compose up -d --force-recreate

          echo "✅ Deployment completed successfully."
          EOF
