name: Build & Push Backend to GAR

on:
  push:
    branches: [ "main" ]

jobs:

  # -------------------------------
  # 1) CHECKOUT CODE
  # -------------------------------
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Save workspace
        uses: actions/upload-artifact@v3
        with:
          name: source-code
          path: .

  # -------------------------------
  # 2) DECODE .env + BUILD + PUSH
  # -------------------------------
  build-and-push:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Download workspace
        uses: actions/download-artifact@v3
        with:
          name: source-code

      - name: Decode .env file from Base64
        run: |
          echo "${{ secrets.ENV_FILE_BASE64 }}" | base64 -d > .env
          ls -al
          cat .env  # <-- remove this line later (just verifying .env is correct)

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build Docker Image
        run: |
          docker build -t us-central1-docker.pkg.dev/traeta-data/traeta-gar/traeta-backend:latest .

      - name: Push Docker Image
        run: |
          docker push us-central1-docker.pkg.dev/traeta-data/traeta-gar/traeta-backend:latest

  # -------------------------------
  # 3) DEPLOY TO GCP VM (SSH & RESTART)
  # -------------------------------
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Setup SSH
        run: |
          eval $(ssh-agent -s)
          echo "${{ secrets.GCP_VM_SSH_PRIVATE_KEY }}" | tr -d '\r' | ssh-add -
          mkdir -p ~/.ssh
          echo "${{ secrets.GCP_VM_SSH_HOST_KEY }}" >> ~/.ssh/known_hosts

      - name: SSH into VM & Deploy
        run: |
          ssh ansible@YOUR_VM_IP << 'EOF'
          cd /opt/traeta-backend
          echo "${{ secrets.ENV_FILE_BASE64 }}" | base64 -d > .env
          docker-compose pull
          docker-compose down
          docker-compose up -d
          EOF
