name: Build, Push Docker to GAR, and Deploy

on:
  push:
    branches:
      - "main"

jobs:
  checkout:
    runs-on: self-hosted-gcp

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

  build_and_push:
    needs: checkout
    runs-on: self-hosted-gcp

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Configure Docker for GAR
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build Docker image
        run: |
          docker build -t us-central1-docker.pkg.dev/traeta-data/traeta-gar/traeta-backend:latest .

      - name: Push Docker image to GAR
        run: |
          docker push us-central1-docker.pkg.dev/traeta-data/traeta-gar/traeta-backend:latest

  deploy:
    needs: build_and_push
    runs-on: self-hosted-gcp

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Configure Docker for GAR
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Pull latest Docker image
        run: docker pull us-central1-docker.pkg.dev/traeta-data/traeta-gar/traeta-backend:latest

      # ✅ Create .env from GitHub Secret
      - name: Create .env file
        run: |
          echo "${{ secrets.MY_ENV_VARS }}" > .env
          sed -i 's/\r$//' .env

      - name: Install Docker Compose
        run: |
          if ! command -v docker-compose &> /dev/null
          then
            sudo apt-get update
            sudo apt-get install -y docker-compose
          fi

      - name: Deploy containers using Docker Compose
        run: |
          docker-compose down || true
          docker-compose up -d
